
Integer score = 95;

if (score >= 90) {
    System.debug('Grade: A');
} else if (score >= 80) {
    System.debug('Grade: B');
} else if (score >= 70) {
    System.debug('Grade: C');
} else if (score >= 60) {
    System.debug('Grade: D');
} else {
    System.debug('Grade: F');
}

Integer age = 27;
Integer bobAge = 30;

if (age > bobAge) {
    System.debug('I am older than Bob')
} else {
    System.debug('Bob is older than me')
}